VIDEOS_DIR = "data-videos"
DATASET_DIR = "dataset"
DATASET_ANNOTATIONS_FOLDER = "dataset-annotations"
DATASET_ANNOTATIONS_FILE = "current.json"
EXIT_KEY = "q"

# Step 1
FORCE_DATASET_REBUILD = False
FRAMES_PER_VIDEO = 100
BOUNDING_BOX_FORMAT = "xywh"

# Step 2
FORCE_DATASET_ANNOTATIONS_REBUILD = False
BATCH_SIZE = 4
CONFIDENCE = 0.5
IMG_RESIZE = (480, 640)
PERSON_CLASS = 0

# Step 3
TRAIN_RATIO = 0.75
SEED = 100
MAIN_MODEL_PATH_PASCALVOC = "./results/yolov8_detector.keras"
MAIN_MODEL_PATH_ULTRALYTICS = "./main_model.onnx"
